### ISSUE TITLE
Promise { <pending> }

### ISSUE THREAD

**Issue by mertyildiran** [chrisgreg/get-pixel-promise#1]
```
var getPixelPromise = require('get-pixel-promise')
var imageFile = 'dog64.png';

var promise = getPixelPromise('dog64.png');
var imageShape = promise.then((image) => image.shape);

console.log(imageShape);

```

Out: `Promise { <pending> }`

**Comment by chrisgreg** [comment]
This module returns the result as a promise.

To access a value in a promise you need to wait for it to finish and use it.

So to log out the value of the pixel promise result you'd need to do it in the then method of your promise.

Like this:
`var imageShape = promise.then((image) => console.log(image));`
